from fastapi import APIRouter
import json

router = APIRouter()

value = [
    "red bell pepper",
    "garlic",
    "uncooked bacon",
    "unsalted butter",
    "guacamole",
    "deli turkey",
    "white bread",
    "quinoa salad",
    "fried egg",
    "granola",
    "red onion",
    "kalamata olives",
    "onion",
    "naan",
    "cucumber",
    "grilled chicken breast",
    "cherry coke zero",
    "rice",
    "kimchi",
    "nut",
    "filet mignon",
    "ketchup",
    "taco",
    "white rice",
    "dates",
    "k cup",
    "decaf coffee",
    "celery",
    "juice",
    "flour",
    "mixed nuts",
    "grapes",
    "bacon",
    "apple juice",
    "potato",
    "fried zucchini",
    "avocado dip",
    "wheat bread",
    "quinoa pasta",
    "quaker old fashioned oats",
    "uncooked rice",
    "kale salad",
    "bun bo xao",
    "butter",
    "quinoa patty",
    "red wine",
    "yu xiang pork",
    "idli",
    "nonfat yogurt",
    "tortilla chips",
    "avocado toast",
    "italian bread",
    "applesauce unsweetened",
    "dry pasta",
    "hummus",
    "egg",
    "chicken breast",
    "sour cream",
    "dunkin donuts iced coffee",
    "brown sugar",
    "cherry tomatoes",
    "lentil",
    "cream cheese",
    "deli ham",
    "walnut",
    "whole avocado",
    "sugar free jello",
    "chicken thigh",
    "turkey bacon",
    "vodka",
    "ice",
    "zucchini lasagna",
    "ground chicken",
    "lettuce mix",
    "mixed greens",
    "chicken",
    "banh hoi xuong nuong",
    "zucchini fries",
    "lime juice",
    "diet coke",
    "ham",
    "0 greek yogurt",
    "all purpose flour",
    "kosher salt",
    "nutmeg",
    "french bread",
    "kale strawberry banana smoothie",
    "raspberry",
    "wine",
    "pine nuts",
    "cauliflower",
    "roasted vegetables",
    "ranch dressing",
    "unsalted almonds",
    "almond milk",
    "french toast",
    "mashed potato",
    "chocolate",
    "veggies",
    "pear",
    "homemade chili",
    "chicken quesadilla",
    "kidney beans",
    "kfc",
    "quesadilla",
    "roti",
    "fairlife fat free ultra filtered milk",
    "honey ham",
    "beef jerky",
    "dark chocolate",
    "hamburger bun",
    "hamburger patty",
    "coconut milk",
    "italian sausage",
    "jasmine rice",
    "whole wheat bread",
    "scrambled egg",
    "grilled chicken",
    "tomato sauce",
    "cherry tomato",
    "dal",
    "banana",
    "brown rice",
    "lemon zest",
    "yellow pepper",
    "yogurt smoothie",
    "premier protein chocolate shake",
    "coffee",
    "zucchini soup",
    "iceberg",
    "caesar dressing",
    "green grapes",
    "dijon mustard",
    "almond flour",
    "raw kale",
    "half and half",
    "dos xx",
    "ground turkey",
    "fish",
    "frozen yogurt",
    "vanilla yogurt",
    "dressing",
    "egg white",
    "ground beef",
    "shredded cheese",
    "yellow squash",
    "avocado juice",
    "yogurt strawberry",
    "hot dog",
    "vegetable oil",
    "rotisserie chicken",
    "oat",
    "almond milk unsweetened",
    "unsweetened almond milk",
    "steak",
    "red wine vinegar",
    "ginger",
    "pineapple",
    "nachos",
    "kiwi",
    "italian seasoning",
    "wheat",
    "oatmeal",
    "shrimp",
    "meatloaf",
    "ice cream cookies",
    "green beans",
    "tomato",
    "mozzarella",
    "rice krispie",
    "fried chicken breast",
    "dove eggs",
    "grilled veggies",
    "peach",
    "nectarine",
    "bread",
    "kielbasa",
    "xanthan gum",
    "xylitol",
    "green onion",
    "lime",
    "jelly",
    "eggnog",
    "xoi",
    "banh xeo",
    "orange",
    "roast beef",
    "cauliflower rice",
    "grapefruit",
    "pizza",
    "yogurt blueberry",
    "garlic powder",
    "toast",
    "salad",
    "colby jack",
    "red rice",
    "cabbage",
    "olive",
    "carrot",
    "hard boiled",
    "strawberry",
    "dark chocolate chip cookies",
    "corn",
    "eggplant",
    "red quinoa",
    "green bean",
    "baked chicken",
    "tea",
    "pork",
    "lamb",
    "quiche",
    "salt",
    "poached eggs",
    "romaine",
    "greek yogurt",
    "cheddar cheese",
    "lettuce salad",
    "vegetable soup",
    "latte",
    "sausage",
    "fried rice",
    "ga xe phay",
    "eggo",
    "nutella",
    "iceberg lettuce",
    "tofu",
    "uncooked oatmeal",
    "kit kat",
    "quick oats",
    "yoplait yogurt",
    "yellow onion",
    "quinoa chip",
    "new potatoes",
    "salsa",
    "quinoa bowl",
    "protein",
    "large egg",
    "macadamia nuts",
    "grilled zucchini",
    "lemon juice",
    "green tea",
    "white sugar",
    "cheese",
    "sliced ham",
    "yeast",
    "fried fish",
    "broccoli",
    "liquid egg whites",
    "orange juice",
    "mango",
    "olive oil",
    "watermelon",
    "strawberry jelly",
    "strawberry jam",
    "iceberg lettuce leaf",
    "plain greek yogurt",
    "tuna",
    "xtra cheddar goldfish",
    "hass avocado",
    "lean ground beef",
    "avocado oil",
    "chicken broth",
    "romaine lettuce",
    "cooked quinoa",
    "balsamic vinegar",
    "ghee",
    "zero coke",
    "banana juice",
    "kombucha",
    "pepperoni",
    "pineapple orange juice",
    "quinoa stirfry",
    "kale",
    "pasta",
    "udon",
    "xiao bai cai",
    "instant oatmeal",
    "sauteed zucchini",
    "uncooked quinoa",
    "green apple",
    "mashed potatoes",
    "vanilla",
    "quinoa burger",
    "olive oil vinegar",
    "zoodles",
    "lemon",
    "instant coffee",
    "scramble eggs",
    "lobster",
    "tomato juice",
    "popcorn",
    "xiaolongbao",
    "lasagna",
    "uncooked chickpeas",
    "kefir",
    "upma",
    "ranch",
    "zucchini muffin",
    "boiled egg",
    "lemonade",
    "fries",
    "quinoa",
    "sugar",
    "dos xx lager",
    "mushroom",
    "pork chop",
    "white wine",
    "natural peanut butter",
    "queso",
    "ziti pasta",
    "mayo",
    "sweet potato starch noodles",
    "orange jello",
    "extra virgin olive oil",
    "queso fresco",
    "chicken salad",
    "2% greek yogurt",
    "oil",
    "pepper",
    "questbar",
    "turkey breast",
    "dal rice",
    "pork loin",
    "noodle",
    "yam",
    "lettuce",
    "banana oatmeal",
    "zucchini bread",
    "coffee with cream",
    "mustard",
    "icing sugar",
    "jam",
    "italian dressing",
    "beef",
    "diced tomatoes",
    "plain yogurt",
    "coconut oil",
    "goat cheese",
    "veg",
    "sweet potato",
    "vinegar",
    "milk",
    "peanut",
    "apple cider vinegar",
    "honeycrisp apples",
    "spinach",
    "basmati rice",
    "quail eggs",
    "fried chicken",
    "water",
    "ice tea",
    "vitamin water zero xxx acai blueberry pomegranate",
    "zucchini",
    "coffee ice creams",
    "1% milk",
    "peanut butter",
    "ice cream cone",
    "egg whites",
    "blueberry",
    "hamburger meat",
    "chicken nuggets",
    "whole milk",
    "jalapeno",
    "skim milk",
    "tortilla",
    "unsweetened coconut milk",
    "honey",
    "feta",
    "nutritional yeast",
    "peas",
    "chicken wings",
    "honeydew",
    "ice cream",
    "hamburger",
    "yogurt almonds",
    "xiaomain",
    "donut",
    "roll",
    "salmon",
    "chicken noodle soup",
    "unsweetened tea",
    "deviled egg",
    "michelob ultra",
    "heavy cream",
    "meat",
    "turkey",
    "spaghetti noodles",
    "whole chicken",
    "apple oatmeal",
    "yogurt",
    "fried bananas",
    "spaghetti",
    "uncooked pasta",
    "Acerola – West Indian Cherry",
    "Apple",
    "Apricots",
    "Avocado",
    "Blackberries",
    "Blackcurrant",
    "Blueberries",
    "Breadfruit",
    "Cantaloupe",
    "Carambola",
    "Cherimoya",
    "Cherries",
    "Clementine",
    "Coconut Meat",
    "Cranberries",
    "Custard-Apple",
    "Date Fruit",
    "Durian",
    "Elderberries",
    "Feijoa",
    "Figs",
    "Gooseberries",
    "Guava",
    "Honeydew Melon",
    "Jackfruit",
    "Java-Plum",
    "Jujube Fruit",
    "Kiwifruit",
    "Kumquat",
    "Longan",
    "Loquat",
    "Lychee",
    "Mandarin",
    "Mangosteen",
    "Mulberries",
    "Olives",
    "Papaya",
    "Passion Fruit",
    "Peaches",
    "Persimmon",
    "Pitaya (Dragonfruit)",
    "Pitanga",
    "Plantain",
    "Plums",
    "Pomegranate",
    "Prickly Pear",
    "Prunes",
    "Pummelo",
    "Quince",
    "Raspberries",
    "Rhubarb",
    "Rose-Apple",
    "Sapodilla",
    "Sapote, Mamey",
    "Soursop",
    "Strawberries",
    "Sugar-Apple",
    "Tamarind",
    "Tangerine",
    "Amaranth Leaves",
    "Arrowroot",
    "Artichoke",
    "Arugula",
    "Asparagus",
    "Bamboo Shoots",
    "Beans, Green",
    "Beets",
    "Bitter Melon",
    "Bok Choy",
    "Broadbeans (Fava Beans)",
    "Broccoli Rabe",
    "Brussel Sprouts",
    "Cabbage, Green",
    "Cabbage, Red",
    "Cassava (Yuca Root)",
    "Celeriac (Celery Root)",
    "Chayote",
    "Chicory (Curly Endive)",
    "Collards",
    "Crookneck",
    "Daikon",
    "Dandelion Greens",
    "Edamame, Soybeans",
    "Endives",
    "Fennel",
    "Fiddleheads",
    "Ginger Root",
    "Horseradish",
    "Jicama",
    "Kohlrabi",
    "Leeks",
    "Lettuce, Iceberg",
    "Lettuce, Leaf",
    "Lettuce, Romaine",
    "Mushrooms",
    "Mustard Greens",
    "Okra",
    "Onion (Red)",
    "Onions",
    "Parsnip",
    "Peas, Green",
    "Pepper, Green",
    "Pepper, Sweet Red",
    "Potato, Red",
    "Potato, White",
    "Potato, Yellow",
    "Pumpkin",
    "Radicchio",
    "Radishes",
    "Rutabaga",
    "Salsify (Oysterplant)",
    "Shallots",
    "Snow Peas",
    "Sorrel (Dock)",
    "Spaghetti Squash",
    "Squash, Butternut",
    "Sugar Snap Peas",
    "Swiss Chard",
    "Tomatillo",
    "Turnip",
    "Watercress",
    "Yam Root",
]


@router.get("/All_Items", response_description="All Food Items")
async def get_all_food_items():
    return {"code": 200, "Food Items": value}


@router.get("/{name}", response_description="Search Food Items")
async def search_food_items(name):
    path = str("D:\\New folder (3)\\Project\\Server\\Data") + chr(92) + name + ".json"
    try:
        if open(path):
            data = json.load(open(path))
            return {"food_items": data, "code": 200}
        else:
            return {"code": 200, "food_items": "Not Found"}

    except Exception as e:
        return {"code": 404, "Error": "(Error: " + str(e) + ")"}
